name: Deploy to Raspberry Pi

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: SSH into Raspberry Pi and Deploy
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.PI_HOST }}
          username: ${{ secrets.PI_USERNAME }}
          key: ${{ secrets.PAPER }}
          port: ${{ secrets.PI_SSH_PORT }}
          script: |
            cd /var/www/html/meme_game
            git pull origin Slave
            # Additional commands to deploy your project
